DROP TABLE book;
DROP TABLE issue;
DROP TABLE reader;

CREATE TABLE IF NOT EXISTS book
(
    id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(256) NOT NULL
);

INSERT INTO book (title)
VALUES ('Тихий Дон'),
       ('Поднятая Целина'),
       ('Мастер и Маргарита'),
       ('Война и Мир'),
       ('Молодая Гвардия');


CREATE TABLE IF NOT EXISTS reader
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(256),
    last_name  VARCHAR(256)
);

INSERT INTO reader (first_name, last_name)
VALUES ('Евгений', 'Миронов'),
       ('Анна', 'Ковальчук'),
       ('Владимир', 'Машков'),
       ('Константин', 'Хабенский'),
       ('Светлана', 'Ходченкова');

CREATE TABLE IF NOT EXISTS issue
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book_id     BIGINT NOT NULL,
    reader_id   BIGINT NOT NULL,
    issued_at   DATE,
    returned_at DATE
);

